// ═══════════════════════════════════════════════════════════
// LEVEL 2 — Phrases & Sentences (~250 entries)
// Builds on Level 1 vocabulary with longer expressions
// ═══════════════════════════════════════════════════════════
const level2Data = {
  introductions: {
    title: "Introducing Yourself",
    titleCn: "自我介绍",
    emoji: "🙋",
    description: "Tell people about yourself!",
    words: [
      { chinese: "我叫小明", pinyin: "wǒ jiào xiǎo míng", english: "My name is Xiao Ming" },
      { chinese: "你叫什么名字", pinyin: "nǐ jiào shén me míng zi", english: "What is your name" },
      { chinese: "我今年七岁", pinyin: "wǒ jīn nián qī suì", english: "I am seven years old" },
      { chinese: "你几岁", pinyin: "nǐ jǐ suì", english: "How old are you" },
      { chinese: "我是学生", pinyin: "wǒ shì xué shēng", english: "I am a student" },
      { chinese: "我住在这里", pinyin: "wǒ zhù zài zhè lǐ", english: "I live here" },
      { chinese: "我是中国人", pinyin: "wǒ shì zhōng guó rén", english: "I am Chinese" },
      { chinese: "我喜欢画画", pinyin: "wǒ xǐ huān huà huà", english: "I like to draw" },
      { chinese: "很高兴认识你", pinyin: "hěn gāo xìng rèn shi nǐ", english: "Nice to meet you" },
      { chinese: "我家有四口人", pinyin: "wǒ jiā yǒu sì kǒu rén", english: "My family has four people" },
      { chinese: "我有一个哥哥", pinyin: "wǒ yǒu yī gè gē ge", english: "I have an older brother" },
      { chinese: "我有一个妹妹", pinyin: "wǒ yǒu yī gè mèi mei", english: "I have a younger sister" },
      { chinese: "我的爱好是唱歌", pinyin: "wǒ de ài hào shì chàng gē", english: "My hobby is singing" },
      { chinese: "我在上小学", pinyin: "wǒ zài shàng xiǎo xué", english: "I attend primary school" },
      { chinese: "我喜欢运动", pinyin: "wǒ xǐ huān yùn dòng", english: "I like sports" },
      { chinese: "这是我的朋友", pinyin: "zhè shì wǒ de péng yǒu", english: "This is my friend" },
      { chinese: "他是我的同学", pinyin: "tā shì wǒ de tóng xué", english: "He is my classmate" },
      { chinese: "她叫小花", pinyin: "tā jiào xiǎo huā", english: "Her name is Xiao Hua" },
      { chinese: "我来自北京", pinyin: "wǒ lái zì běi jīng", english: "I come from Beijing" },
      { chinese: "请多多指教", pinyin: "qǐng duō duō zhǐ jiào", english: "Please guide me" },
      { chinese: "我的生日是三月五号", pinyin: "wǒ de shēng rì shì sān yuè wǔ hào", english: "My birthday is March 5th" },
      { chinese: "我最喜欢吃冰淇淋", pinyin: "wǒ zuì xǐ huān chī bīng qí lín", english: "I like eating ice cream the most" },
      { chinese: "我会说中文", pinyin: "wǒ huì shuō zhōng wén", english: "I can speak Chinese" },
      { chinese: "我也会说英文", pinyin: "wǒ yě huì shuō yīng wén", english: "I can also speak English" },
      { chinese: "我的老师很好", pinyin: "wǒ de lǎo shī hěn hǎo", english: "My teacher is very nice" },
    ]
  },
  atSchool: {
    title: "At School",
    titleCn: "在学校",
    emoji: "📚",
    description: "Phrases you use at school!",
    words: [
      { chinese: "上课了", pinyin: "shàng kè le", english: "Class is starting" },
      { chinese: "下课了", pinyin: "xià kè le", english: "Class is over" },
      { chinese: "请打开书", pinyin: "qǐng dǎ kāi shū", english: "Please open your book" },
      { chinese: "请翻到第三页", pinyin: "qǐng fān dào dì sān yè", english: "Please turn to page three" },
      { chinese: "我不明白", pinyin: "wǒ bù míng bai", english: "I don't understand" },
      { chinese: "请再说一次", pinyin: "qǐng zài shuō yī cì", english: "Please say it again" },
      { chinese: "老师好", pinyin: "lǎo shī hǎo", english: "Hello teacher" },
      { chinese: "我知道了", pinyin: "wǒ zhī dào le", english: "I understand now" },
      { chinese: "我有一个问题", pinyin: "wǒ yǒu yī gè wèn tí", english: "I have a question" },
      { chinese: "这个字怎么写", pinyin: "zhè ge zì zěn me xiě", english: "How do you write this character" },
      { chinese: "请举手", pinyin: "qǐng jǔ shǒu", english: "Please raise your hand" },
      { chinese: "我做完了", pinyin: "wǒ zuò wán le", english: "I am done" },
      { chinese: "今天的作业是什么", pinyin: "jīn tiān de zuò yè shì shén me", english: "What is today's homework" },
      { chinese: "我忘了带书", pinyin: "wǒ wàng le dài shū", english: "I forgot to bring my book" },
      { chinese: "我可以去厕所吗", pinyin: "wǒ kě yǐ qù cè suǒ ma", english: "May I go to the toilet" },
      { chinese: "请安静", pinyin: "qǐng ān jìng", english: "Please be quiet" },
      { chinese: "跟我读", pinyin: "gēn wǒ dú", english: "Read after me" },
      { chinese: "我们一起学习吧", pinyin: "wǒ men yī qǐ xué xí ba", english: "Let's study together" },
      { chinese: "明天有考试", pinyin: "míng tiān yǒu kǎo shì", english: "There is an exam tomorrow" },
      { chinese: "我考了一百分", pinyin: "wǒ kǎo le yī bǎi fēn", english: "I scored one hundred" },
      { chinese: "你最喜欢什么课", pinyin: "nǐ zuì xǐ huān shén me kè", english: "What is your favorite subject" },
      { chinese: "我最喜欢数学", pinyin: "wǒ zuì xǐ huān shù xué", english: "I like math the most" },
      { chinese: "放学了", pinyin: "fàng xué le", english: "School is out" },
      { chinese: "我们出去玩吧", pinyin: "wǒ men chū qù wán ba", english: "Let's go play outside" },
      { chinese: "排好队", pinyin: "pái hǎo duì", english: "Line up properly" },
    ]
  },
  atHome: {
    title: "At Home",
    titleCn: "在家里",
    emoji: "🏡",
    description: "Things you say at home!",
    words: [
      { chinese: "我回来了", pinyin: "wǒ huí lái le", english: "I'm home" },
      { chinese: "吃饭了", pinyin: "chī fàn le", english: "Time to eat" },
      { chinese: "我饿了", pinyin: "wǒ è le", english: "I am hungry" },
      { chinese: "我渴了", pinyin: "wǒ kě le", english: "I am thirsty" },
      { chinese: "请帮我一下", pinyin: "qǐng bāng wǒ yī xià", english: "Please help me" },
      { chinese: "我要喝水", pinyin: "wǒ yào hē shuǐ", english: "I want to drink water" },
      { chinese: "该睡觉了", pinyin: "gāi shuì jiào le", english: "Time to go to sleep" },
      { chinese: "做完作业了吗", pinyin: "zuò wán zuò yè le ma", english: "Have you finished homework" },
      { chinese: "请关灯", pinyin: "qǐng guān dēng", english: "Please turn off the light" },
      { chinese: "请开门", pinyin: "qǐng kāi mén", english: "Please open the door" },
      { chinese: "妈妈我回来了", pinyin: "mā ma wǒ huí lái le", english: "Mom I'm home" },
      { chinese: "今天好累", pinyin: "jīn tiān hǎo lèi", english: "I'm so tired today" },
      { chinese: "我想看电视", pinyin: "wǒ xiǎng kàn diàn shì", english: "I want to watch TV" },
      { chinese: "可以玩一会儿吗", pinyin: "kě yǐ wán yī huì er ma", english: "Can I play for a while" },
      { chinese: "该起床了", pinyin: "gāi qǐ chuáng le", english: "Time to get up" },
      { chinese: "我去洗手", pinyin: "wǒ qù xǐ shǒu", english: "I'm going to wash my hands" },
      { chinese: "饭做好了", pinyin: "fàn zuò hǎo le", english: "The food is ready" },
      { chinese: "请收拾你的房间", pinyin: "qǐng shōu shi nǐ de fáng jiān", english: "Please clean your room" },
      { chinese: "我要刷牙", pinyin: "wǒ yào shuā yá", english: "I need to brush my teeth" },
      { chinese: "晚安妈妈", pinyin: "wǎn ān mā ma", english: "Good night Mom" },
      { chinese: "谁在敲门", pinyin: "shéi zài qiāo mén", english: "Who is knocking on the door" },
      { chinese: "我的书包在哪里", pinyin: "wǒ de shū bāo zài nǎ lǐ", english: "Where is my schoolbag" },
      { chinese: "我不想吃这个", pinyin: "wǒ bù xiǎng chī zhè ge", english: "I don't want to eat this" },
      { chinese: "这个很好吃", pinyin: "zhè ge hěn hǎo chī", english: "This is very delicious" },
      { chinese: "我自己来", pinyin: "wǒ zì jǐ lái", english: "I'll do it myself" },
    ]
  },
  shopping: {
    title: "Shopping & Eating Out",
    titleCn: "购物和吃饭",
    emoji: "🛒",
    description: "At the shop and restaurant!",
    words: [
      { chinese: "这个多少钱", pinyin: "zhè ge duō shǎo qián", english: "How much is this" },
      { chinese: "太贵了", pinyin: "tài guì le", english: "Too expensive" },
      { chinese: "便宜一点吧", pinyin: "pián yi yī diǎn ba", english: "Make it cheaper" },
      { chinese: "我要买这个", pinyin: "wǒ yào mǎi zhè ge", english: "I want to buy this" },
      { chinese: "请给我一杯水", pinyin: "qǐng gěi wǒ yī bēi shuǐ", english: "Please give me a glass of water" },
      { chinese: "我要两个苹果", pinyin: "wǒ yào liǎng gè píng guǒ", english: "I want two apples" },
      { chinese: "你们有什么", pinyin: "nǐ men yǒu shén me", english: "What do you have" },
      { chinese: "菜单在哪里", pinyin: "cài dān zài nǎ lǐ", english: "Where is the menu" },
      { chinese: "我要一碗面", pinyin: "wǒ yào yī wǎn miàn", english: "I want a bowl of noodles" },
      { chinese: "买单", pinyin: "mǎi dān", english: "Check please" },
      { chinese: "不要辣的", pinyin: "bù yào là de", english: "Not spicy please" },
      { chinese: "我吃饱了", pinyin: "wǒ chī bǎo le", english: "I am full" },
      { chinese: "再来一个", pinyin: "zài lái yī gè", english: "One more please" },
      { chinese: "打包带走", pinyin: "dǎ bāo dài zǒu", english: "Take away please" },
      { chinese: "这个好吃吗", pinyin: "zhè ge hǎo chī ma", english: "Is this delicious" },
      { chinese: "我要点菜", pinyin: "wǒ yào diǎn cài", english: "I want to order food" },
      { chinese: "请等一下", pinyin: "qǐng děng yī xià", english: "Please wait a moment" },
      { chinese: "有没有果汁", pinyin: "yǒu méi yǒu guǒ zhī", english: "Do you have juice" },
      { chinese: "我想要一杯茶", pinyin: "wǒ xiǎng yào yī bēi chá", english: "I'd like a cup of tea" },
      { chinese: "请给我筷子", pinyin: "qǐng gěi wǒ kuài zi", english: "Please give me chopsticks" },
      { chinese: "味道很好", pinyin: "wèi dào hěn hǎo", english: "It tastes great" },
      { chinese: "可以用现金吗", pinyin: "kě yǐ yòng xiàn jīn ma", english: "Can I pay with cash" },
      { chinese: "我不吃肉", pinyin: "wǒ bù chī ròu", english: "I don't eat meat" },
      { chinese: "你想吃什么", pinyin: "nǐ xiǎng chī shén me", english: "What do you want to eat" },
      { chinese: "谢谢你的招待", pinyin: "xiè xie nǐ de zhāo dài", english: "Thank you for the treat" },
    ]
  },
  directions: {
    title: "Directions & Travel",
    titleCn: "方向和旅行",
    emoji: "🗺️",
    description: "Finding your way around!",
    words: [
      { chinese: "请问怎么走", pinyin: "qǐng wèn zěn me zǒu", english: "Excuse me, how do I get there" },
      { chinese: "往左走", pinyin: "wǎng zuǒ zǒu", english: "Go left" },
      { chinese: "往右走", pinyin: "wǎng yòu zǒu", english: "Go right" },
      { chinese: "一直往前走", pinyin: "yī zhí wǎng qián zǒu", english: "Go straight ahead" },
      { chinese: "在哪里", pinyin: "zài nǎ lǐ", english: "Where is it" },
      { chinese: "离这里远吗", pinyin: "lí zhè lǐ yuǎn ma", english: "Is it far from here" },
      { chinese: "我迷路了", pinyin: "wǒ mí lù le", english: "I am lost" },
      { chinese: "请带我去", pinyin: "qǐng dài wǒ qù", english: "Please take me there" },
      { chinese: "厕所在哪里", pinyin: "cè suǒ zài nǎ lǐ", english: "Where is the toilet" },
      { chinese: "公园在前面", pinyin: "gōng yuán zài qián miàn", english: "The park is ahead" },
      { chinese: "学校在后面", pinyin: "xué xiào zài hòu miàn", english: "The school is behind" },
      { chinese: "银行在旁边", pinyin: "yín háng zài páng biān", english: "The bank is next to it" },
      { chinese: "我们坐公共汽车吧", pinyin: "wǒ men zuò gōng gòng qì chē ba", english: "Let's take the bus" },
      { chinese: "到了吗", pinyin: "dào le ma", english: "Are we there yet" },
      { chinese: "还有多远", pinyin: "hái yǒu duō yuǎn", english: "How much further" },
      { chinese: "我要去火车站", pinyin: "wǒ yào qù huǒ chē zhàn", english: "I want to go to the train station" },
      { chinese: "请在这里停", pinyin: "qǐng zài zhè lǐ tíng", english: "Please stop here" },
      { chinese: "上车", pinyin: "shàng chē", english: "Get on the vehicle" },
      { chinese: "下车", pinyin: "xià chē", english: "Get off the vehicle" },
      { chinese: "前面就是了", pinyin: "qián miàn jiù shì le", english: "It's right up ahead" },
      { chinese: "你去哪里", pinyin: "nǐ qù nǎ lǐ", english: "Where are you going" },
      { chinese: "我要回家", pinyin: "wǒ yào huí jiā", english: "I want to go home" },
      { chinese: "在左边", pinyin: "zài zuǒ biān", english: "On the left side" },
      { chinese: "在右边", pinyin: "zài yòu biān", english: "On the right side" },
      { chinese: "过马路要小心", pinyin: "guò mǎ lù yào xiǎo xīn", english: "Be careful crossing the road" },
    ]
  },
  weather: {
    title: "Weather & Seasons",
    titleCn: "天气和季节",
    emoji: "🌤️",
    description: "Talk about the weather!",
    words: [
      { chinese: "今天天气很好", pinyin: "jīn tiān tiān qì hěn hǎo", english: "The weather is nice today" },
      { chinese: "今天下雨了", pinyin: "jīn tiān xià yǔ le", english: "It's raining today" },
      { chinese: "外面很冷", pinyin: "wài miàn hěn lěng", english: "It's very cold outside" },
      { chinese: "外面很热", pinyin: "wài miàn hěn rè", english: "It's very hot outside" },
      { chinese: "要下雪了", pinyin: "yào xià xuě le", english: "It's going to snow" },
      { chinese: "风很大", pinyin: "fēng hěn dà", english: "The wind is strong" },
      { chinese: "今天有太阳", pinyin: "jīn tiān yǒu tài yáng", english: "It's sunny today" },
      { chinese: "天很蓝", pinyin: "tiān hěn lán", english: "The sky is very blue" },
      { chinese: "要带雨伞", pinyin: "yào dài yǔ sǎn", english: "Bring an umbrella" },
      { chinese: "穿多一点", pinyin: "chuān duō yī diǎn", english: "Wear more clothes" },
      { chinese: "春天来了", pinyin: "chūn tiān lái le", english: "Spring is here" },
      { chinese: "夏天很热", pinyin: "xià tiān hěn rè", english: "Summer is very hot" },
      { chinese: "秋天的叶子很漂亮", pinyin: "qiū tiān de yè zi hěn piào liang", english: "Autumn leaves are beautiful" },
      { chinese: "冬天会下雪", pinyin: "dōng tiān huì xià xuě", english: "It snows in winter" },
      { chinese: "彩虹出来了", pinyin: "cǎi hóng chū lái le", english: "The rainbow is out" },
      { chinese: "今天多云", pinyin: "jīn tiān duō yún", english: "It's cloudy today" },
      { chinese: "明天会下雨吗", pinyin: "míng tiān huì xià yǔ ma", english: "Will it rain tomorrow" },
      { chinese: "太阳出来了", pinyin: "tài yáng chū lái le", english: "The sun came out" },
      { chinese: "花开了", pinyin: "huā kāi le", english: "The flowers bloomed" },
      { chinese: "树叶掉了", pinyin: "shù yè diào le", english: "The leaves have fallen" },
      { chinese: "今天很暖和", pinyin: "jīn tiān hěn nuǎn huo", english: "It's warm today" },
      { chinese: "今天很凉快", pinyin: "jīn tiān hěn liáng kuai", english: "It's cool today" },
      { chinese: "我喜欢春天", pinyin: "wǒ xǐ huān chūn tiān", english: "I like spring" },
      { chinese: "冬天可以堆雪人", pinyin: "dōng tiān kě yǐ duī xuě rén", english: "We can build a snowman in winter" },
      { chinese: "夏天可以去游泳", pinyin: "xià tiān kě yǐ qù yóu yǒng", english: "We can go swimming in summer" },
    ]
  },
  friends: {
    title: "Making Friends",
    titleCn: "交朋友",
    emoji: "🤝",
    description: "Chat and play with friends!",
    words: [
      { chinese: "你想一起玩吗", pinyin: "nǐ xiǎng yī qǐ wán ma", english: "Do you want to play together" },
      { chinese: "我们做朋友吧", pinyin: "wǒ men zuò péng yǒu ba", english: "Let's be friends" },
      { chinese: "你喜欢什么", pinyin: "nǐ xǐ huān shén me", english: "What do you like" },
      { chinese: "我喜欢踢足球", pinyin: "wǒ xǐ huān tī zú qiú", english: "I like playing soccer" },
      { chinese: "一起来吧", pinyin: "yī qǐ lái ba", english: "Come join us" },
      { chinese: "你真厉害", pinyin: "nǐ zhēn lì hai", english: "You are really great" },
      { chinese: "太好了", pinyin: "tài hǎo le", english: "That's great" },
      { chinese: "没问题", pinyin: "méi wèn tí", english: "No problem" },
      { chinese: "别担心", pinyin: "bié dān xīn", english: "Don't worry" },
      { chinese: "加油", pinyin: "jiā yóu", english: "You can do it" },
      { chinese: "你真聪明", pinyin: "nǐ zhēn cōng míng", english: "You are really smart" },
      { chinese: "我们是好朋友", pinyin: "wǒ men shì hǎo péng yǒu", english: "We are good friends" },
      { chinese: "你住在哪里", pinyin: "nǐ zhù zài nǎ lǐ", english: "Where do you live" },
      { chinese: "明天见", pinyin: "míng tiān jiàn", english: "See you tomorrow" },
      { chinese: "生日快乐", pinyin: "shēng rì kuài lè", english: "Happy birthday" },
      { chinese: "新年快乐", pinyin: "xīn nián kuài lè", english: "Happy New Year" },
      { chinese: "你的爱好是什么", pinyin: "nǐ de ài hào shì shén me", english: "What is your hobby" },
      { chinese: "我喜欢看书", pinyin: "wǒ xǐ huān kàn shū", english: "I like reading books" },
      { chinese: "我们一起画画吧", pinyin: "wǒ men yī qǐ huà huà ba", english: "Let's draw together" },
      { chinese: "你真有趣", pinyin: "nǐ zhēn yǒu qù", english: "You are really funny" },
      { chinese: "我等你", pinyin: "wǒ děng nǐ", english: "I'll wait for you" },
      { chinese: "对不起我来晚了", pinyin: "duì bù qǐ wǒ lái wǎn le", english: "Sorry I'm late" },
      { chinese: "不要生气了", pinyin: "bù yào shēng qì le", english: "Don't be angry anymore" },
      { chinese: "我帮你吧", pinyin: "wǒ bāng nǐ ba", english: "Let me help you" },
      { chinese: "谢谢你的帮助", pinyin: "xiè xie nǐ de bāng zhù", english: "Thank you for your help" },
    ]
  },
  dailyRoutine: {
    title: "Daily Routine",
    titleCn: "日常生活",
    emoji: "🌅",
    description: "What you do every day!",
    words: [
      { chinese: "我每天六点起床", pinyin: "wǒ měi tiān liù diǎn qǐ chuáng", english: "I wake up at six every day" },
      { chinese: "先刷牙洗脸", pinyin: "xiān shuā yá xǐ liǎn", english: "First brush teeth and wash face" },
      { chinese: "我吃早饭了", pinyin: "wǒ chī zǎo fàn le", english: "I had breakfast" },
      { chinese: "我要去上学了", pinyin: "wǒ yào qù shàng xué le", english: "I'm going to school now" },
      { chinese: "中午吃午饭", pinyin: "zhōng wǔ chī wǔ fàn", english: "Eat lunch at noon" },
      { chinese: "下午三点放学", pinyin: "xià wǔ sān diǎn fàng xué", english: "School ends at three PM" },
      { chinese: "回家先做作业", pinyin: "huí jiā xiān zuò zuò yè", english: "Do homework first when home" },
      { chinese: "然后出去玩", pinyin: "rán hòu chū qù wán", english: "Then go outside to play" },
      { chinese: "六点吃晚饭", pinyin: "liù diǎn chī wǎn fàn", english: "Eat dinner at six" },
      { chinese: "晚上看一会儿书", pinyin: "wǎn shang kàn yī huì er shū", english: "Read a book in the evening" },
      { chinese: "九点钟睡觉", pinyin: "jiǔ diǎn zhōng shuì jiào", english: "Go to sleep at nine o'clock" },
      { chinese: "我每天都洗澡", pinyin: "wǒ měi tiān dōu xǐ zǎo", english: "I take a bath every day" },
      { chinese: "周末我不上学", pinyin: "zhōu mò wǒ bù shàng xué", english: "I don't go to school on weekends" },
      { chinese: "星期六我去公园", pinyin: "xīng qī liù wǒ qù gōng yuán", english: "I go to the park on Saturday" },
      { chinese: "星期天和家人在一起", pinyin: "xīng qī tiān hé jiā rén zài yī qǐ", english: "I'm with family on Sunday" },
      { chinese: "我每天都喝牛奶", pinyin: "wǒ měi tiān dōu hē niú nǎi", english: "I drink milk every day" },
      { chinese: "我喜欢骑自行车去上学", pinyin: "wǒ xǐ huān qí zì xíng chē qù shàng xué", english: "I like to ride a bike to school" },
      { chinese: "我每天走路去学校", pinyin: "wǒ měi tiān zǒu lù qù xué xiào", english: "I walk to school every day" },
      { chinese: "吃饭前要洗手", pinyin: "chī fàn qián yào xǐ shǒu", english: "Wash hands before eating" },
      { chinese: "我帮妈妈做家务", pinyin: "wǒ bāng mā ma zuò jiā wù", english: "I help Mom with chores" },
      { chinese: "我喜欢周末", pinyin: "wǒ xǐ huān zhōu mò", english: "I like weekends" },
      { chinese: "早睡早起身体好", pinyin: "zǎo shuì zǎo qǐ shēn tǐ hǎo", english: "Sleep early rise early for good health" },
      { chinese: "我每天运动半小时", pinyin: "wǒ měi tiān yùn dòng bàn xiǎo shí", english: "I exercise for half an hour daily" },
      { chinese: "我今天很开心", pinyin: "wǒ jīn tiān hěn kāi xīn", english: "I am very happy today" },
      { chinese: "该穿校服了", pinyin: "gāi chuān xiào fú le", english: "Time to put on the school uniform" },
    ]
  },
  questions: {
    title: "Asking Questions",
    titleCn: "问问题",
    emoji: "❓",
    description: "How to ask all kinds of questions!",
    words: [
      { chinese: "这是什么", pinyin: "zhè shì shén me", english: "What is this" },
      { chinese: "那是什么", pinyin: "nà shì shén me", english: "What is that" },
      { chinese: "为什么", pinyin: "wèi shén me", english: "Why" },
      { chinese: "怎么办", pinyin: "zěn me bàn", english: "What should we do" },
      { chinese: "你在做什么", pinyin: "nǐ zài zuò shén me", english: "What are you doing" },
      { chinese: "你吃了吗", pinyin: "nǐ chī le ma", english: "Have you eaten" },
      { chinese: "你去过中国吗", pinyin: "nǐ qù guò zhōng guó ma", english: "Have you been to China" },
      { chinese: "现在几点了", pinyin: "xiàn zài jǐ diǎn le", english: "What time is it now" },
      { chinese: "这个怎么说", pinyin: "zhè ge zěn me shuō", english: "How do you say this" },
      { chinese: "你有兄弟姐妹吗", pinyin: "nǐ yǒu xiōng dì jiě mèi ma", english: "Do you have siblings" },
      { chinese: "你会游泳吗", pinyin: "nǐ huì yóu yǒng ma", english: "Can you swim" },
      { chinese: "你要去哪里", pinyin: "nǐ yào qù nǎ lǐ", english: "Where are you going" },
      { chinese: "你什么时候来", pinyin: "nǐ shén me shí hòu lái", english: "When are you coming" },
      { chinese: "谁来了", pinyin: "shéi lái le", english: "Who came" },
      { chinese: "你能帮我吗", pinyin: "nǐ néng bāng wǒ ma", english: "Can you help me" },
      { chinese: "好不好", pinyin: "hǎo bù hǎo", english: "Is that okay" },
      { chinese: "你有没有铅笔", pinyin: "nǐ yǒu méi yǒu qiān bǐ", english: "Do you have a pencil" },
      { chinese: "这个对吗", pinyin: "zhè ge duì ma", english: "Is this correct" },
      { chinese: "你要喝什么", pinyin: "nǐ yào hē shén me", english: "What do you want to drink" },
      { chinese: "你准备好了吗", pinyin: "nǐ zhǔn bèi hǎo le ma", english: "Are you ready" },
      { chinese: "你看见了吗", pinyin: "nǐ kàn jiàn le ma", english: "Did you see it" },
      { chinese: "他是谁", pinyin: "tā shì shéi", english: "Who is he" },
      { chinese: "你怎么了", pinyin: "nǐ zěn me le", english: "What happened to you" },
      { chinese: "多大了", pinyin: "duō dà le", english: "How old" },
      { chinese: "你明白了吗", pinyin: "nǐ míng bai le ma", english: "Do you understand" },
    ]
  },
  describing: {
    title: "Describing Things",
    titleCn: "描述事物",
    emoji: "🎭",
    description: "Words to describe the world!",
    words: [
      { chinese: "这朵花很漂亮", pinyin: "zhè duǒ huā hěn piào liang", english: "This flower is very pretty" },
      { chinese: "那只猫很可爱", pinyin: "nà zhī māo hěn kě ài", english: "That cat is very cute" },
      { chinese: "这个苹果很大", pinyin: "zhè ge píng guǒ hěn dà", english: "This apple is very big" },
      { chinese: "这条路很长", pinyin: "zhè tiáo lù hěn cháng", english: "This road is very long" },
      { chinese: "这本书很有趣", pinyin: "zhè běn shū hěn yǒu qù", english: "This book is very interesting" },
      { chinese: "我的房间很干净", pinyin: "wǒ de fáng jiān hěn gān jìng", english: "My room is very clean" },
      { chinese: "他跑得很快", pinyin: "tā pǎo de hěn kuài", english: "He runs very fast" },
      { chinese: "她唱歌唱得很好", pinyin: "tā chàng gē chàng de hěn hǎo", english: "She sings very well" },
      { chinese: "今天的饭很好吃", pinyin: "jīn tiān de fàn hěn hǎo chī", english: "Today's meal is delicious" },
      { chinese: "这个蛋糕很甜", pinyin: "zhè ge dàn gāo hěn tián", english: "This cake is very sweet" },
      { chinese: "这杯水很凉", pinyin: "zhè bēi shuǐ hěn liáng", english: "This glass of water is cool" },
      { chinese: "我的书包很重", pinyin: "wǒ de shū bāo hěn zhòng", english: "My schoolbag is very heavy" },
      { chinese: "这个故事很感人", pinyin: "zhè ge gù shi hěn gǎn rén", english: "This story is very touching" },
      { chinese: "这幅画很好看", pinyin: "zhè fú huà hěn hǎo kàn", english: "This painting looks great" },
      { chinese: "他很高", pinyin: "tā hěn gāo", english: "He is very tall" },
      { chinese: "她很友好", pinyin: "tā hěn yǒu hǎo", english: "She is very friendly" },
      { chinese: "这里很安静", pinyin: "zhè lǐ hěn ān jìng", english: "It's very quiet here" },
      { chinese: "外面很吵", pinyin: "wài miàn hěn chǎo", english: "It's very noisy outside" },
      { chinese: "这条裙子很好看", pinyin: "zhè tiáo qún zi hěn hǎo kàn", english: "This dress looks very nice" },
      { chinese: "我的狗很听话", pinyin: "wǒ de gǒu hěn tīng huà", english: "My dog is very obedient" },
      { chinese: "这个问题很简单", pinyin: "zhè ge wèn tí hěn jiǎn dān", english: "This question is very easy" },
      { chinese: "那个问题很难", pinyin: "nà ge wèn tí hěn nán", english: "That question is very hard" },
      { chinese: "这个东西很轻", pinyin: "zhè ge dōng xi hěn qīng", english: "This thing is very light" },
      { chinese: "水果很新鲜", pinyin: "shuǐ guǒ hěn xīn xiān", english: "The fruit is very fresh" },
      { chinese: "我的家很温暖", pinyin: "wǒ de jiā hěn wēn nuǎn", english: "My home is very warm" },
    ]
  }
};
