// ═══════════════════════════════════════════════════════════
// LEVEL 1 — Basic Vocabulary (~300 single words)
// ═══════════════════════════════════════════════════════════
const level1Data = {
  greetings: {
    title: "Greetings & Politeness",
    titleCn: "问候与礼貌",
    emoji: "👋",
    description: "Say hello and be polite!",
    words: [
      { chinese: "你好", pinyin: "nǐ hǎo", english: "Hello" },
      { chinese: "再见", pinyin: "zài jiàn", english: "Goodbye" },
      { chinese: "谢谢", pinyin: "xiè xie", english: "Thank you" },
      { chinese: "对不起", pinyin: "duì bù qǐ", english: "Sorry" },
      { chinese: "请", pinyin: "qǐng", english: "Please" },
      { chinese: "早上好", pinyin: "zǎo shàng hǎo", english: "Good morning" },
      { chinese: "晚安", pinyin: "wǎn ān", english: "Good night" },
      { chinese: "你好吗", pinyin: "nǐ hǎo ma", english: "How are you" },
      { chinese: "没关系", pinyin: "méi guān xi", english: "It's okay" },
      { chinese: "不客气", pinyin: "bù kè qi", english: "You're welcome" },
      { chinese: "下午好", pinyin: "xià wǔ hǎo", english: "Good afternoon" },
      { chinese: "晚上好", pinyin: "wǎn shàng hǎo", english: "Good evening" },
      { chinese: "欢迎", pinyin: "huān yíng", english: "Welcome" },
      { chinese: "嗨", pinyin: "hāi", english: "Hi" },
      { chinese: "拜拜", pinyin: "bài bài", english: "Bye bye" },
      { chinese: "好的", pinyin: "hǎo de", english: "Okay" },
      { chinese: "是", pinyin: "shì", english: "Yes" },
      { chinese: "不是", pinyin: "bù shì", english: "No" },
      { chinese: "先生", pinyin: "xiān sheng", english: "Mr. / Sir" },
      { chinese: "女士", pinyin: "nǚ shì", english: "Ms. / Madam" },
    ]
  },
  numbers: {
    title: "Numbers",
    titleCn: "数字",
    emoji: "🔢",
    description: "Count from 1 to 100 and beyond!",
    words: [
      { chinese: "一", pinyin: "yī", english: "One (1)" },
      { chinese: "二", pinyin: "èr", english: "Two (2)" },
      { chinese: "三", pinyin: "sān", english: "Three (3)" },
      { chinese: "四", pinyin: "sì", english: "Four (4)" },
      { chinese: "五", pinyin: "wǔ", english: "Five (5)" },
      { chinese: "六", pinyin: "liù", english: "Six (6)" },
      { chinese: "七", pinyin: "qī", english: "Seven (7)" },
      { chinese: "八", pinyin: "bā", english: "Eight (8)" },
      { chinese: "九", pinyin: "jiǔ", english: "Nine (9)" },
      { chinese: "十", pinyin: "shí", english: "Ten (10)" },
      { chinese: "十一", pinyin: "shí yī", english: "Eleven (11)" },
      { chinese: "十二", pinyin: "shí èr", english: "Twelve (12)" },
      { chinese: "二十", pinyin: "èr shí", english: "Twenty (20)" },
      { chinese: "三十", pinyin: "sān shí", english: "Thirty (30)" },
      { chinese: "四十", pinyin: "sì shí", english: "Forty (40)" },
      { chinese: "五十", pinyin: "wǔ shí", english: "Fifty (50)" },
      { chinese: "一百", pinyin: "yī bǎi", english: "One hundred (100)" },
      { chinese: "一千", pinyin: "yī qiān", english: "One thousand (1000)" },
      { chinese: "零", pinyin: "líng", english: "Zero (0)" },
      { chinese: "第一", pinyin: "dì yī", english: "First" },
      { chinese: "第二", pinyin: "dì èr", english: "Second" },
      { chinese: "两", pinyin: "liǎng", english: "Two (measure)" },
      { chinese: "半", pinyin: "bàn", english: "Half" },
      { chinese: "多少", pinyin: "duō shǎo", english: "How many" },
      { chinese: "几", pinyin: "jǐ", english: "How many (small)" },
    ]
  },
  colors: {
    title: "Colors & Shapes",
    titleCn: "颜色和形状",
    emoji: "🎨",
    description: "Learn the rainbow and shapes!",
    words: [
      { chinese: "红色", pinyin: "hóng sè", english: "Red", color: "#E74C3C" },
      { chinese: "蓝色", pinyin: "lán sè", english: "Blue", color: "#3498DB" },
      { chinese: "绿色", pinyin: "lǜ sè", english: "Green", color: "#2ECC71" },
      { chinese: "黄色", pinyin: "huáng sè", english: "Yellow", color: "#F1C40F" },
      { chinese: "白色", pinyin: "bái sè", english: "White", color: "#ECF0F1" },
      { chinese: "黑色", pinyin: "hēi sè", english: "Black", color: "#2C3E50" },
      { chinese: "粉色", pinyin: "fěn sè", english: "Pink", color: "#FF6B9D" },
      { chinese: "橙色", pinyin: "chéng sè", english: "Orange", color: "#E67E22" },
      { chinese: "紫色", pinyin: "zǐ sè", english: "Purple", color: "#9B59B6" },
      { chinese: "灰色", pinyin: "huī sè", english: "Gray", color: "#95A5A6" },
      { chinese: "棕色", pinyin: "zōng sè", english: "Brown", color: "#8B4513" },
      { chinese: "圆形", pinyin: "yuán xíng", english: "Circle" },
      { chinese: "正方形", pinyin: "zhèng fāng xíng", english: "Square" },
      { chinese: "三角形", pinyin: "sān jiǎo xíng", english: "Triangle" },
      { chinese: "星星", pinyin: "xīng xīng", english: "Star" },
    ]
  },
  family: {
    title: "Family & People",
    titleCn: "家人和人物",
    emoji: "👨‍👩‍👧‍👦",
    description: "Meet the family and other people!",
    words: [
      { chinese: "爸爸", pinyin: "bà ba", english: "Dad" },
      { chinese: "妈妈", pinyin: "mā ma", english: "Mom" },
      { chinese: "哥哥", pinyin: "gē ge", english: "Older brother" },
      { chinese: "姐姐", pinyin: "jiě jie", english: "Older sister" },
      { chinese: "弟弟", pinyin: "dì di", english: "Younger brother" },
      { chinese: "妹妹", pinyin: "mèi mei", english: "Younger sister" },
      { chinese: "朋友", pinyin: "péng yǒu", english: "Friend" },
      { chinese: "爷爷", pinyin: "yé ye", english: "Grandfather (paternal)" },
      { chinese: "奶奶", pinyin: "nǎi nai", english: "Grandmother (paternal)" },
      { chinese: "外公", pinyin: "wài gōng", english: "Grandfather (maternal)" },
      { chinese: "外婆", pinyin: "wài pó", english: "Grandmother (maternal)" },
      { chinese: "叔叔", pinyin: "shū shu", english: "Uncle" },
      { chinese: "阿姨", pinyin: "ā yí", english: "Aunt" },
      { chinese: "宝宝", pinyin: "bǎo bao", english: "Baby" },
      { chinese: "老师", pinyin: "lǎo shī", english: "Teacher" },
      { chinese: "同学", pinyin: "tóng xué", english: "Classmate" },
      { chinese: "医生", pinyin: "yī shēng", english: "Doctor" },
      { chinese: "男孩", pinyin: "nán hái", english: "Boy" },
      { chinese: "女孩", pinyin: "nǚ hái", english: "Girl" },
      { chinese: "人", pinyin: "rén", english: "Person" },
    ]
  },
  animals: {
    title: "Animals",
    titleCn: "动物",
    emoji: "🐾",
    description: "Discover animal names!",
    words: [
      { chinese: "猫", pinyin: "māo", english: "Cat" },
      { chinese: "狗", pinyin: "gǒu", english: "Dog" },
      { chinese: "鱼", pinyin: "yú", english: "Fish" },
      { chinese: "鸟", pinyin: "niǎo", english: "Bird" },
      { chinese: "兔子", pinyin: "tù zi", english: "Rabbit" },
      { chinese: "马", pinyin: "mǎ", english: "Horse" },
      { chinese: "鸡", pinyin: "jī", english: "Chicken" },
      { chinese: "鸭子", pinyin: "yā zi", english: "Duck" },
      { chinese: "猪", pinyin: "zhū", english: "Pig" },
      { chinese: "牛", pinyin: "niú", english: "Cow" },
      { chinese: "羊", pinyin: "yáng", english: "Sheep" },
      { chinese: "蛇", pinyin: "shé", english: "Snake" },
      { chinese: "老虎", pinyin: "lǎo hǔ", english: "Tiger" },
      { chinese: "大象", pinyin: "dà xiàng", english: "Elephant" },
      { chinese: "猴子", pinyin: "hóu zi", english: "Monkey" },
      { chinese: "熊猫", pinyin: "xióng māo", english: "Panda" },
      { chinese: "狮子", pinyin: "shī zi", english: "Lion" },
      { chinese: "蝴蝶", pinyin: "hú dié", english: "Butterfly" },
      { chinese: "蚂蚁", pinyin: "mǎ yǐ", english: "Ant" },
      { chinese: "龙", pinyin: "lóng", english: "Dragon" },
    ]
  },
  food: {
    title: "Food & Drinks",
    titleCn: "食物和饮料",
    emoji: "🍜",
    description: "Yummy things to eat and drink!",
    words: [
      { chinese: "水", pinyin: "shuǐ", english: "Water" },
      { chinese: "米饭", pinyin: "mǐ fàn", english: "Rice" },
      { chinese: "面", pinyin: "miàn", english: "Noodles" },
      { chinese: "苹果", pinyin: "píng guǒ", english: "Apple" },
      { chinese: "牛奶", pinyin: "niú nǎi", english: "Milk" },
      { chinese: "鸡蛋", pinyin: "jī dàn", english: "Egg" },
      { chinese: "面包", pinyin: "miàn bāo", english: "Bread" },
      { chinese: "肉", pinyin: "ròu", english: "Meat" },
      { chinese: "鱼肉", pinyin: "yú ròu", english: "Fish meat" },
      { chinese: "鸡肉", pinyin: "jī ròu", english: "Chicken meat" },
      { chinese: "蔬菜", pinyin: "shū cài", english: "Vegetables" },
      { chinese: "水果", pinyin: "shuǐ guǒ", english: "Fruit" },
      { chinese: "香蕉", pinyin: "xiāng jiāo", english: "Banana" },
      { chinese: "西瓜", pinyin: "xī guā", english: "Watermelon" },
      { chinese: "葡萄", pinyin: "pú tao", english: "Grapes" },
      { chinese: "草莓", pinyin: "cǎo méi", english: "Strawberry" },
      { chinese: "茶", pinyin: "chá", english: "Tea" },
      { chinese: "果汁", pinyin: "guǒ zhī", english: "Juice" },
      { chinese: "蛋糕", pinyin: "dàn gāo", english: "Cake" },
      { chinese: "糖", pinyin: "táng", english: "Candy / Sugar" },
      { chinese: "饺子", pinyin: "jiǎo zi", english: "Dumplings" },
      { chinese: "汤", pinyin: "tāng", english: "Soup" },
      { chinese: "盐", pinyin: "yán", english: "Salt" },
      { chinese: "冰淇淋", pinyin: "bīng qí lín", english: "Ice cream" },
      { chinese: "饼干", pinyin: "bǐng gān", english: "Biscuit / Cookie" },
    ]
  },
  bodyParts: {
    title: "Body Parts",
    titleCn: "身体部位",
    emoji: "🦶",
    description: "Learn about your body!",
    words: [
      { chinese: "头", pinyin: "tóu", english: "Head" },
      { chinese: "头发", pinyin: "tóu fa", english: "Hair" },
      { chinese: "眼睛", pinyin: "yǎn jīng", english: "Eyes" },
      { chinese: "耳朵", pinyin: "ěr duo", english: "Ears" },
      { chinese: "鼻子", pinyin: "bí zi", english: "Nose" },
      { chinese: "嘴巴", pinyin: "zuǐ ba", english: "Mouth" },
      { chinese: "牙齿", pinyin: "yá chǐ", english: "Teeth" },
      { chinese: "舌头", pinyin: "shé tou", english: "Tongue" },
      { chinese: "脸", pinyin: "liǎn", english: "Face" },
      { chinese: "手", pinyin: "shǒu", english: "Hand" },
      { chinese: "手指", pinyin: "shǒu zhǐ", english: "Finger" },
      { chinese: "脚", pinyin: "jiǎo", english: "Foot" },
      { chinese: "腿", pinyin: "tuǐ", english: "Leg" },
      { chinese: "肚子", pinyin: "dù zi", english: "Tummy" },
      { chinese: "背", pinyin: "bèi", english: "Back" },
      { chinese: "肩膀", pinyin: "jiān bǎng", english: "Shoulder" },
      { chinese: "膝盖", pinyin: "xī gài", english: "Knee" },
      { chinese: "脖子", pinyin: "bó zi", english: "Neck" },
      { chinese: "心", pinyin: "xīn", english: "Heart" },
      { chinese: "身体", pinyin: "shēn tǐ", english: "Body" },
    ]
  },
  clothes: {
    title: "Clothes",
    titleCn: "衣服",
    emoji: "👕",
    description: "What are you wearing today?",
    words: [
      { chinese: "衣服", pinyin: "yī fu", english: "Clothes" },
      { chinese: "裤子", pinyin: "kù zi", english: "Pants" },
      { chinese: "裙子", pinyin: "qún zi", english: "Skirt / Dress" },
      { chinese: "鞋子", pinyin: "xié zi", english: "Shoes" },
      { chinese: "袜子", pinyin: "wà zi", english: "Socks" },
      { chinese: "帽子", pinyin: "mào zi", english: "Hat" },
      { chinese: "外套", pinyin: "wài tào", english: "Jacket / Coat" },
      { chinese: "衬衫", pinyin: "chèn shān", english: "Shirt" },
      { chinese: "毛衣", pinyin: "máo yī", english: "Sweater" },
      { chinese: "围巾", pinyin: "wéi jīn", english: "Scarf" },
      { chinese: "手套", pinyin: "shǒu tào", english: "Gloves" },
      { chinese: "书包", pinyin: "shū bāo", english: "Schoolbag" },
      { chinese: "雨伞", pinyin: "yǔ sǎn", english: "Umbrella" },
      { chinese: "眼镜", pinyin: "yǎn jìng", english: "Glasses" },
      { chinese: "拉链", pinyin: "lā liàn", english: "Zipper" },
    ]
  },
  school: {
    title: "School",
    titleCn: "学校",
    emoji: "🏫",
    description: "Things you see at school!",
    words: [
      { chinese: "学校", pinyin: "xué xiào", english: "School" },
      { chinese: "书", pinyin: "shū", english: "Book" },
      { chinese: "笔", pinyin: "bǐ", english: "Pen" },
      { chinese: "铅笔", pinyin: "qiān bǐ", english: "Pencil" },
      { chinese: "纸", pinyin: "zhǐ", english: "Paper" },
      { chinese: "桌子", pinyin: "zhuō zi", english: "Desk / Table" },
      { chinese: "椅子", pinyin: "yǐ zi", english: "Chair" },
      { chinese: "黑板", pinyin: "hēi bǎn", english: "Blackboard" },
      { chinese: "教室", pinyin: "jiào shì", english: "Classroom" },
      { chinese: "作业", pinyin: "zuò yè", english: "Homework" },
      { chinese: "考试", pinyin: "kǎo shì", english: "Exam / Test" },
      { chinese: "课", pinyin: "kè", english: "Class / Lesson" },
      { chinese: "橡皮", pinyin: "xiàng pí", english: "Eraser" },
      { chinese: "尺子", pinyin: "chǐ zi", english: "Ruler" },
      { chinese: "字", pinyin: "zì", english: "Character / Word" },
      { chinese: "数学", pinyin: "shù xué", english: "Math" },
      { chinese: "英语", pinyin: "yīng yǔ", english: "English" },
      { chinese: "中文", pinyin: "zhōng wén", english: "Chinese" },
      { chinese: "音乐", pinyin: "yīn yuè", english: "Music" },
      { chinese: "画", pinyin: "huà", english: "Drawing / Painting" },
    ]
  },
  home: {
    title: "Home & Furniture",
    titleCn: "家和家具",
    emoji: "🏠",
    description: "Things around the house!",
    words: [
      { chinese: "家", pinyin: "jiā", english: "Home / Family" },
      { chinese: "房子", pinyin: "fáng zi", english: "House" },
      { chinese: "门", pinyin: "mén", english: "Door" },
      { chinese: "窗户", pinyin: "chuāng hu", english: "Window" },
      { chinese: "床", pinyin: "chuáng", english: "Bed" },
      { chinese: "灯", pinyin: "dēng", english: "Light / Lamp" },
      { chinese: "电视", pinyin: "diàn shì", english: "Television" },
      { chinese: "电话", pinyin: "diàn huà", english: "Phone" },
      { chinese: "电脑", pinyin: "diàn nǎo", english: "Computer" },
      { chinese: "冰箱", pinyin: "bīng xiāng", english: "Refrigerator" },
      { chinese: "厕所", pinyin: "cè suǒ", english: "Toilet / Bathroom" },
      { chinese: "厨房", pinyin: "chú fáng", english: "Kitchen" },
      { chinese: "客厅", pinyin: "kè tīng", english: "Living room" },
      { chinese: "卧室", pinyin: "wò shì", english: "Bedroom" },
      { chinese: "钥匙", pinyin: "yào shi", english: "Key" },
      { chinese: "杯子", pinyin: "bēi zi", english: "Cup / Glass" },
      { chinese: "碗", pinyin: "wǎn", english: "Bowl" },
      { chinese: "筷子", pinyin: "kuài zi", english: "Chopsticks" },
      { chinese: "勺子", pinyin: "sháo zi", english: "Spoon" },
      { chinese: "盘子", pinyin: "pán zi", english: "Plate" },
    ]
  },
  nature: {
    title: "Nature & Weather",
    titleCn: "自然和天气",
    emoji: "🌈",
    description: "The world around you!",
    words: [
      { chinese: "天", pinyin: "tiān", english: "Sky / Day" },
      { chinese: "太阳", pinyin: "tài yáng", english: "Sun" },
      { chinese: "月亮", pinyin: "yuè liang", english: "Moon" },
      { chinese: "星星", pinyin: "xīng xīng", english: "Stars" },
      { chinese: "云", pinyin: "yún", english: "Cloud" },
      { chinese: "雨", pinyin: "yǔ", english: "Rain" },
      { chinese: "雪", pinyin: "xuě", english: "Snow" },
      { chinese: "风", pinyin: "fēng", english: "Wind" },
      { chinese: "花", pinyin: "huā", english: "Flower" },
      { chinese: "草", pinyin: "cǎo", english: "Grass" },
      { chinese: "树", pinyin: "shù", english: "Tree" },
      { chinese: "山", pinyin: "shān", english: "Mountain" },
      { chinese: "河", pinyin: "hé", english: "River" },
      { chinese: "海", pinyin: "hǎi", english: "Sea / Ocean" },
      { chinese: "石头", pinyin: "shí tou", english: "Rock / Stone" },
      { chinese: "火", pinyin: "huǒ", english: "Fire" },
      { chinese: "土", pinyin: "tǔ", english: "Earth / Soil" },
      { chinese: "热", pinyin: "rè", english: "Hot" },
      { chinese: "冷", pinyin: "lěng", english: "Cold" },
      { chinese: "春天", pinyin: "chūn tiān", english: "Spring" },
    ]
  },
  actions: {
    title: "Actions (Verbs)",
    titleCn: "动作",
    emoji: "🏃",
    description: "Things you can do!",
    words: [
      { chinese: "吃", pinyin: "chī", english: "Eat" },
      { chinese: "喝", pinyin: "hē", english: "Drink" },
      { chinese: "看", pinyin: "kàn", english: "Look / Watch" },
      { chinese: "听", pinyin: "tīng", english: "Listen" },
      { chinese: "说", pinyin: "shuō", english: "Say / Speak" },
      { chinese: "读", pinyin: "dú", english: "Read" },
      { chinese: "写", pinyin: "xiě", english: "Write" },
      { chinese: "走", pinyin: "zǒu", english: "Walk" },
      { chinese: "跑", pinyin: "pǎo", english: "Run" },
      { chinese: "跳", pinyin: "tiào", english: "Jump" },
      { chinese: "坐", pinyin: "zuò", english: "Sit" },
      { chinese: "站", pinyin: "zhàn", english: "Stand" },
      { chinese: "睡觉", pinyin: "shuì jiào", english: "Sleep" },
      { chinese: "起床", pinyin: "qǐ chuáng", english: "Wake up" },
      { chinese: "玩", pinyin: "wán", english: "Play" },
      { chinese: "学", pinyin: "xué", english: "Study / Learn" },
      { chinese: "唱歌", pinyin: "chàng gē", english: "Sing" },
      { chinese: "跳舞", pinyin: "tiào wǔ", english: "Dance" },
      { chinese: "画画", pinyin: "huà huà", english: "Draw / Paint" },
      { chinese: "买", pinyin: "mǎi", english: "Buy" },
      { chinese: "给", pinyin: "gěi", english: "Give" },
      { chinese: "开", pinyin: "kāi", english: "Open" },
      { chinese: "关", pinyin: "guān", english: "Close" },
      { chinese: "笑", pinyin: "xiào", english: "Laugh / Smile" },
      { chinese: "哭", pinyin: "kū", english: "Cry" },
    ]
  },
  time: {
    title: "Time & Days",
    titleCn: "时间和日子",
    emoji: "🕐",
    description: "When is it?",
    words: [
      { chinese: "今天", pinyin: "jīn tiān", english: "Today" },
      { chinese: "明天", pinyin: "míng tiān", english: "Tomorrow" },
      { chinese: "昨天", pinyin: "zuó tiān", english: "Yesterday" },
      { chinese: "现在", pinyin: "xiàn zài", english: "Now" },
      { chinese: "早上", pinyin: "zǎo shang", english: "Morning" },
      { chinese: "中午", pinyin: "zhōng wǔ", english: "Noon" },
      { chinese: "下午", pinyin: "xià wǔ", english: "Afternoon" },
      { chinese: "晚上", pinyin: "wǎn shang", english: "Evening / Night" },
      { chinese: "星期一", pinyin: "xīng qī yī", english: "Monday" },
      { chinese: "星期二", pinyin: "xīng qī èr", english: "Tuesday" },
      { chinese: "星期三", pinyin: "xīng qī sān", english: "Wednesday" },
      { chinese: "星期四", pinyin: "xīng qī sì", english: "Thursday" },
      { chinese: "星期五", pinyin: "xīng qī wǔ", english: "Friday" },
      { chinese: "星期六", pinyin: "xīng qī liù", english: "Saturday" },
      { chinese: "星期天", pinyin: "xīng qī tiān", english: "Sunday" },
      { chinese: "年", pinyin: "nián", english: "Year" },
      { chinese: "月", pinyin: "yuè", english: "Month" },
      { chinese: "日", pinyin: "rì", english: "Day" },
      { chinese: "小时", pinyin: "xiǎo shí", english: "Hour" },
      { chinese: "分钟", pinyin: "fēn zhōng", english: "Minute" },
    ]
  },
  feelings: {
    title: "Feelings",
    titleCn: "感觉",
    emoji: "😊",
    description: "How do you feel?",
    words: [
      { chinese: "高兴", pinyin: "gāo xìng", english: "Happy" },
      { chinese: "难过", pinyin: "nán guò", english: "Sad" },
      { chinese: "生气", pinyin: "shēng qì", english: "Angry" },
      { chinese: "害怕", pinyin: "hài pà", english: "Scared" },
      { chinese: "累", pinyin: "lèi", english: "Tired" },
      { chinese: "饿", pinyin: "è", english: "Hungry" },
      { chinese: "渴", pinyin: "kě", english: "Thirsty" },
      { chinese: "好", pinyin: "hǎo", english: "Good" },
      { chinese: "坏", pinyin: "huài", english: "Bad" },
      { chinese: "大", pinyin: "dà", english: "Big" },
      { chinese: "小", pinyin: "xiǎo", english: "Small" },
      { chinese: "多", pinyin: "duō", english: "Many / Much" },
      { chinese: "少", pinyin: "shǎo", english: "Few / Little" },
      { chinese: "新", pinyin: "xīn", english: "New" },
      { chinese: "旧", pinyin: "jiù", english: "Old (things)" },
    ]
  },
  places: {
    title: "Places & Transport",
    titleCn: "地方和交通",
    emoji: "🚌",
    description: "Where are you going?",
    words: [
      { chinese: "学校", pinyin: "xué xiào", english: "School" },
      { chinese: "医院", pinyin: "yī yuàn", english: "Hospital" },
      { chinese: "商店", pinyin: "shāng diàn", english: "Shop / Store" },
      { chinese: "超市", pinyin: "chāo shì", english: "Supermarket" },
      { chinese: "公园", pinyin: "gōng yuán", english: "Park" },
      { chinese: "图书馆", pinyin: "tú shū guǎn", english: "Library" },
      { chinese: "餐厅", pinyin: "cān tīng", english: "Restaurant" },
      { chinese: "银行", pinyin: "yín háng", english: "Bank" },
      { chinese: "机场", pinyin: "jī chǎng", english: "Airport" },
      { chinese: "车站", pinyin: "chē zhàn", english: "Bus station" },
      { chinese: "汽车", pinyin: "qì chē", english: "Car" },
      { chinese: "公共汽车", pinyin: "gōng gòng qì chē", english: "Bus" },
      { chinese: "出租车", pinyin: "chū zū chē", english: "Taxi" },
      { chinese: "自行车", pinyin: "zì xíng chē", english: "Bicycle" },
      { chinese: "飞机", pinyin: "fēi jī", english: "Airplane" },
      { chinese: "火车", pinyin: "huǒ chē", english: "Train" },
      { chinese: "船", pinyin: "chuán", english: "Boat / Ship" },
      { chinese: "路", pinyin: "lù", english: "Road" },
      { chinese: "地铁", pinyin: "dì tiě", english: "Subway" },
      { chinese: "中国", pinyin: "zhōng guó", english: "China" },
    ]
  }
};
